baseURL = "https://blog-eyt.pages.dev/"
title = "Enoch"
theme = "PaperMod"

defaultContentLanguage = "zh"
languageCode = "zh-cn"
hasCJKLanguage = true

[pagination]
pagerSize = 10

enableRobotsTXT = true
enableEmoji = true

[params]
  author = ["Enoch"]
  description = "这是我的个人博客"
  env = "production"
  DateFormat = "2006-01-02"

  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = false
  ShowWordCount = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false          # 已关闭面包屑
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  TocOpen = true
  hideSummary = true
  disableSpecial1stPost = true

  [params.profileMode]
    enabled = true
    title = "Enoch"
    subtitle = "我的泉源都在你里面"
    imageUrl = "/images/avatar.jpg"
    imageWidth = 120
    imageHeight = 120

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "查经资料"
  url = "/study/"
  weight = 3

pygmentsUseClasses = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true