baseURL = "https://blog-eyt.pages.dev/"
locale = "zh-CN"
title = "Enoch"
theme = "PaperMod"

# 启用中文支持
defaultContentLanguage = "zh"

[params]
  author = "Enoch"
  description = "这是我的个人博客"

# 配置菜单（首页 + 关于）
[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 2

[[menu.main]]
    name = "圣经阅读"
    url = "/bible.html"
    weight = 3  


[outputs]
  home = ["HTML"]
  page = ["HTML"]

[mediaTypes]
  [mediaTypes."application/json"]
    suffix = "json"

[outputFormats]
  [outputFormats.bible]
    mediaType = "text/html"
    isHTML = true
